version: '3.4'
services:
  app:
    container_name: richmorecms
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/richmorecms
    depends_on:
      - mongo
    volumes:
      - ".:/usr/src/api"
    networks:
      - richnet
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - richnet
    volumes:
      - "./data/mongodb-data:/usr/src/api"

networks:
  richnet:
    driver: bridge